CREATE SCHEMA data_mart;
DROP SCHEMA data_mart;

CREATE TABLE fact_ticket (
	TICKET_ID BIGINT(20) NOT NULL PRIMARY KEY,
    TICKET_NK BIGINT(20) NOT NULL,
    DATE_ID DATE NOT NULL,
    STORE_ID INT(10) NOT NULL,
    CASHIER INT(10) NOT NULL,
    PAYMETHOD VARCHAR(20) NOT NULL,
    TOTAL_PRODUCT DECIMAL(20,5) NOT NULL,
    TOTAL_TAX DECIMAL(20,5) NOT NULL,
    TOTAL_ORDER DECIMAL(20,5) NOT NULL,
    FOREIGN KEY (DATE_ID) REFERENCES dimensional_time(DATE_ID),
    FOREIGN KEY (STORE_ID) REFERENCES dimensional_space(STORE_ID),
    FOREIGN KEY (CASHIER) REFERENCES dimensional_staff(STAFF),
    FOREIGN KEY (PAYMETHOD) REFERENCES dimensional_payment(PAYMETHOD)
);

CREATE TABLE dimensional_time (
	DATE_ID DATE NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(20),
    DAY_OF_WEEK VARCHAR(10) NOT NULL,
    MONTH_OF_YEAR VARCHAR(10) NOT NULL,
    WEEKDAY VARCHAR(10) NOT NULL,
    SEASON VARCHAR(10) NOT NULL,
    HOLIDAY VARCHAR(10) NOT NULL,
    NUMBER_MONTH SMALLINT(6) NOT NULL,
    NUMBER_YEAR SMALLINT(6) NOT NULL,
    NUMBER_YEAR_MONTH SMALLINT(6) NOT NULL,
    NUMBER_DAY_OF_WEEK SMALLINT(6) NOT NULL,
    NUMBER_DAY_OF_MONTH SMALLINT(6) NOT NULL,
    NUMBER_DAY_OF_YEAR SMALLINT(6) NOT NULL,
	NUMBER_WEEK_OF_YEAR SMALLINT(6) NOT NULL,
    NUMBER_LAST_DAY_OF_MONTH SMALLINT(6) NOT NULL
);

CREATE TABLE dimensional_space (
	STORE_ID INT(10) NOT NULL PRIMARY KEY,
    STORE_NK BIGINT(20) NOT NULL,
    ADDRESS VARCHAR(40) NOT NULL,
    ZIPCODE INT(11) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    STATE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL
);

CREATE TABLE dimensional_payment (
	PAYMETHOD VARCHAR(20) NOT NULL PRIMARY KEY,
    BANKNAME VARCHAR(64),
    DESCRIPTION VARCHAR(40)
);

CREATE TABLE dimensional_staff (
	STAFF INT(10) NOT NULL PRIMARY KEY,
    STAFF_NK SMALLINT(6) NOT NULL,
    NAME VARCHAR(40) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    MARITAL_STATUS CHAR(10) NOT NULL,
    DEPARTMENT VARCHAR(20) NOT NULL,
    MANAGER_NAME VARCHAR(20) NOT NULL,
    FOREIGN KEY (STAFF) REFERENCES dimensional_employee(STAFF_EMP)
);

CREATE TABLE dimensional_employee (
	STAFF_EMP INT(10) NOT NULL PRIMARY KEY,
    NIF CHAR(9) NOT NULL,
    GENDER CHAR(1) NOT NULL,
	REMUNERATION INT(11) NOT NULL,
    POSITION_STATUS VARCHAR(20) NOT NULL
);

